[project]
name = "src"
version = "0.0.1"
description = "An offline Rag project for productionizing models"
authors = [{name = "Shriyansh Sen", email = "shriyanshforwork@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}